# Generated by Django 5.1.6 on 2025-04-19 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text='A list of badges earned by the student.', verbose_name='Badges'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(help_text='The email address of the student.', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(help_text='The full name of the student.', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='The profile picture of the student.', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentid',
            field=models.CharField(help_text='The unique student ID.', max_length=20, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(help_text='The user account associated with this student.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
