# Generated by Django 5.2 on 2025-05-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_student_options_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='badges',
            field=models.JSONField(blank=True, default=list, help_text='A list of badges earned by the student.', null=True, verbose_name='Badges'),
        ),
    ]
