# Generated by Django 5.1.7 on 2025-04-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0001_initial'),
        ('event_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubeventpage',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_list_page', to='add_event.event'),
        ),
    ]
