# Generated by Django 5.1.7 on 2025-04-09 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubEventPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_page', to='add_event.event')),
            ],
        ),
    ]
