# Generated by Django 5.1.6 on 2025-04-19 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20250419_1608'),
        ('user_profile', '0002_alter_student_options_alter_student_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='banner',
            field=models.ImageField(blank=True, help_text='The banner image of the club.', null=True, upload_to='club_banners/', verbose_name='Club Banner'),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, help_text='The logo of the club.', null=True, upload_to='club_logos/', verbose_name='Club Logo'),
        ),
        migrations.AlterField(
            model_name='club',
            name='president',
            field=models.ForeignKey(blank=True, help_text='The president of the club.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_clubs', to='user_profile.student', verbose_name='President'),
        ),
        migrations.AlterField(
            model_name='member',
            name='clubs',
            field=models.ManyToManyField(help_text='The clubs the student is a member of.', related_name='members', to='clubs.club', verbose_name='Clubs'),
        ),
        migrations.AlterField(
            model_name='member',
            name='custom_position',
            field=models.CharField(blank=True, help_text='A custom position assigned to the student.', max_length=100, null=True, verbose_name='Custom Position'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Member', 'Member'), ('Executive Committee', 'Executive Committee'), ('Head of Department', 'Head of Department'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Vice President', 'Vice President'), ('President', 'President')], default='Member', help_text='The position of the student in the club.', max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student',
            field=models.ForeignKey(help_text='The student who is a member of the club.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='user_profile.student', verbose_name='Student'),
        ),
    ]
