# Generated by Django 5.2 on 2025-04-27 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_banner_alter_club_description_alter_club_logo_and_more'),
        ('user_profile', '0002_alter_student_options_alter_student_badges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='clubs',
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Member', 'Member'), ('Executive Committee', 'Executive Committee'), ('Head of Department', 'Head of Department'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Vice President', 'Vice President'), ('President', 'President')], default='Member', max_length=50)),
                ('custom_position', models.CharField(blank=True, max_length=100, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.student')),
            ],
            options={
                'unique_together': {('student', 'club')},
            },
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(help_text='Students who are members of this club.', related_name='joined_clubs', through='clubs.ClubMembership', through_fields=('club', 'student'), to='user_profile.student', verbose_name='Members'),
        ),
    ]
