# Generated by Django 5.2 on 2025-04-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_member_clubs_clubmembership_club_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
