# Generated by Django 5.2 on 2025-04-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_delete_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmembership',
            options={'ordering': ['position', 'student__full_name']},
        ),
    ]
