# Generated by Django 5.2 on 2025-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_clubmembership_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255, unique=True)),
                ('dominant_color', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=50, null=True)),
                ('tertiary_color', models.CharField(blank=True, max_length=50, null=True)),
                ('shadow_color', models.CharField(blank=True, max_length=50, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
