# Generated by Django 5.1.6 on 2025-04-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0002_event_club_event_created_by'),
        ('event_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubeventpage',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_page', to='add_event.event'),
        ),
    ]
