# Generated by Django 5.2 on 2025-04-19 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('president', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(choices=[('Member', 'Member'), ('Executive Committee', 'Executive Committee'), ('Head of Department', 'Head of Department'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Vice President', 'Vice President'), ('President', 'President')], default='Member', max_length=50)),
                ('custom_position', models.CharField(blank=True, max_length=100, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='roles.club')),
            ],
        ),
    ]
