# Generated by Django 5.2 on 2025-05-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0003_alter_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, help_text='The banner image of the event.', null=True, upload_to='event_banners/', verbose_name='Event Banner'),
        ),
    ]
