# Generated by Django 5.1.6 on 2025-04-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0002_event_club_event_created_by'),
        ('event_registration', '0001_initial'),
        ('user_profile', '0002_alter_student_options_alter_student_badges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='curtin_id',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='second_name',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='add_event.event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='user_profile.student'),
        ),
    ]
