# Generated by Django 5.1.7 on 2025-03-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='message',
        ),
        migrations.AddField(
            model_name='feedback',
            name='dislike',
            field=models.TextField(default='No dislikes provided'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='experience',
            field=models.TextField(default='No experience provided'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='like',
            field=models.TextField(default='No likes provided'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='role',
            field=models.CharField(choices=[('Organizer', 'Organizer'), ('Volunteer', 'Volunteer'), ('Participant', 'Participant')], default='No role provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='No name provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='satisfaction',
            field=models.CharField(choices=[('Satisfied', 'Satisfied'), ('Fine', 'Fine'), ('Unsatisfied', 'Unsatisfied')], default='No name provided', max_length=50),
        ),
    ]
