# Generated by Django 5.1.6 on 2025-04-21 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0002_event_club_event_created_by'),
        ('feedback', '0002_remove_feedback_created_at_remove_feedback_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='add_event.event'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='role',
            field=models.CharField(choices=[('Organizer', 'Organizer'), ('Volunteer', 'Volunteer'), ('Participant', 'Participant')], default='Participant', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='satisfaction',
            field=models.CharField(choices=[('Satisfied', 'Satisfied'), ('Fine', 'Fine'), ('Unsatisfied', 'Unsatisfied')], default='Fine', max_length=50),
        ),
    ]
