# Generated by Django 5.2 on 2025-05-02 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_name_feedback_event_and_more'),
        ('user_profile', '0002_alter_student_options_alter_student_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='user_profile.student'),
        ),
    ]
